apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployfirst
  name: deployfirst
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployfirst
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployfirst
    spec:
      containers:
      - image: assogbg/pod_first:v1
        name: first
        ports:
        - containerPort: 9999
        resources: {}
status: {}
