apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploysecond
  name: deploysecond
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploysecond
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploysecond
    spec:
      containers:
      - image: assogbg/pod_second:v1
        name: second
        ports:
        - containerPort: 7777
        resources: {}
status: {}
