apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsnginxdown
  labels:
    rs: rsnginxdown
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      rslab: nginxrs
  template:
    metadata:
      labels:
        rslab: nginxrs
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo "important calculation"; sleep 1d
        image: nginx
        name: pod-calc
