apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    id: calc
  name: nginxalone
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
