version: '3.6'
services:
  testCiro:
    build: ./pod7777
    image: test-ciro
    container_name: first-pod
    ports:
            - "7777:7777"
  testSavastano:
    build: ./pod9999
    image: test-savastano
    container_name: second-pod
    ports:
            - "9999:9999"
  testAuth:
    build: ./testAuth
    image: test-auth
    container_name: test-auth
    ports:
            - "2222:2222"
