apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: maincont
  name: maincont
spec:
  volumes:
  - name: logvol
    emptyDir: {}
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo "coucou $(date)" >> /var/log/1.log;
      echo "$(date) INFO yoooo" >> /var/log/2.log; sleep 1; done
    image: busybox
    name: maincontainer
    volumeMounts:
    - mountPath: /var/log
      name: logvol
  - args:
    - /bin/sh
    - -c
    - tail -n+1 -f /var/log/1.log
    image: busybox
    volumeMounts:
    - mountPath: /var/log
      name: logvol
    name: sidecar-log-1
  - args:
    - /bin/sh
    - -c
    - tail -n+1 -f /var/log/2.log
    image: busybox
    name: sidecar-log-2
    volumeMounts:
    -  mountPath: /var/log
       name: logvol
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
