apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backendsecret
  name: backendsecret
spec:
  containers:
  - image: nginx
    name: backendsecret
    resources: {}
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: db-password
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
