apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-bye-dep
  name: np-bye-svc
spec:
  ports:
  - port: 19
    protocol: TCP
    targetPort: 9999
    nodePort: 32000
  selector:
    app: ms-bye-pods
  type: NodePort
