apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: firstpod
  name: firstpod
spec:
  containers:
  - image: assogbg/pod_7777:v1
    name: firstpod
    ports:
    - containerPort: 7777
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
