apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-nodesel
  name: nginx-nodesel
spec:
  containers:
  - image: nginx
    name: nginx-nodesel
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  nodeSelector:
    nodeName: nginxnode
status: {}
