apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: savastano
  name: savastano
spec:
  containers:
  - image: pgolard/test-savastano:v3
    name: savastano
    ports:
    - containerPort: 9999
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
