apiVersion: v1
kind: Pod
metadata:
  name: test-pd-2b
spec:
  containers:
  - image: redis
    name: redis-vol-2b
    volumeMounts:
    - mountPath: /data/redis
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
