apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - image: busybox
    name: firstpod
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /mypodpassword
      name: mysecretvol
  volumes:
  - name: mysecretvol
    secret:
      secretName: mysecretname
