version: '3.6'
services:
  promoAttribution:
    build: ./promotions
    image: promo-attribution
    container_name: promo-attribution
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=rootPassXXX
  logging:
    build: ./logging
    image: promo-logging
    container_name: promo-logging
    depends_on:
      - mongo
    ports:
            - "8000:8000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=rootPassXXX
  mongo:
      image: 'mongo:latest'
      command: --nojournal
      ports:
       - "27017:27017"
      environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
      - MONGO_INITDB_DATABASE=promo
      volumes:
        - mongo-data:/data/crf2
volumes:
  mongo-data:
    driver: local
