version: '3.6'
services:
  promoAttribution:
    build: ./promo_docker
    image: promo-attribution
    container_name: promo-attribution
    depends_on:
      - mongo
    ports:
            - "8080:8080"
    environment:
      - MONGO_LBI_SERVICE_HOST=mongo
      - CRF_DL_GATEWAY_LBI_SERVICE_HOST=crf-dl-gateway
      - CRF_DL_GATEWAY_LBI_SERVICE_PORT=443
      - CRF_DL_GATEWAY_LBI_SERVICE_PORT=80
  mongo:
      image: 'mongo:latest'
      command: --nojournal
      ports:
       - "27017:27017"
      volumes:
        - mongo-data:/data/crf
volumes:
  mongo-data:
    driver: local
