apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secondpod
  name: secondpod
spec:
  containers:
  - image: assogbg/pod_second:v1
    name: secondpod
    ports:
    - containerPort: 7777
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
