apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'cd /toto && echo cd done && ls /toto && sleep 2 && echo "how many do you see" >> titi && sleep 1 && cat titi && sleep 15']
    volumeMounts:
      - mountPath: /toto
        name: scratch-volume
  volumes:
  - name: scratch-volume
    emptyDir: {}

