kind: PersistentVolume
apiVersion: v1
metadata:
  name: hostname-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/first_hostpath"
