apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backendenv
  name: backendenv
spec:
  containers:
  - image: nginx
    name: backendenv
    envFrom:
    - configMapRef:
        name: db-config-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
