apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backendfile
  name: backendfile
spec:
  volumes:
    - name: config-volume
      configMap:
        name: db-config
  containers:
  - image: nginx
    name: backendfile
    volumeMounts:
    - name: config-volume
      mountPath: /tmp/
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
