apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-bye-dep
  name: ms-bye-svc
spec:
  ports:
  - port: 19
    protocol: TCP
    targetPort: 9999
  selector:
    app: ms-bye-pods
  type: ClusterIP
