apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-hello-dep
  name: np-hello-svc
spec:
  ports:
  - port: 17
    protocol: TCP
    targetPort: 7777
    nodePort: 31000
  selector:
    app: ms-hello-pods
  type: NodePort
